# Generated by Django 5.2.8 on 2026-04-01 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="interview",
            name="passing_threshold",
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name="interview",
            name="total_questions",
            field=models.IntegerField(default=5),
        ),
    ]
